name: Create changeset release PR

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions: {} #reset
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    if: github.repository == 'hack-dance/assistants'
    permissions:
      contents: write
      pull-requests: write

    name: Changeset Release
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Setup npmrc
        run: echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Install Dependencies
        run: pnpm i

      - name: Create version PR
        uses: changesets/action@v1
        with:
          version: pnpm version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
